FROM maven:3.8.5-openjdk-18 AS build

WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:18-alpine

WORKDIR /app
COPY --from=build /app/target/transaction-service-1.0.jar .
EXPOSE 8080
CMD ["java", "-jar", "transaction-service-1.0.jar"]
